a = []
x = input()
a.append(str(x.count('a')))
a.append(str(x.count('b')))
a.append(str(x.count('c')))
a.append(str(x.count('d')))
a.append(str(x.count('e')))
a.append(str(x.count('f')))
a.append(str(x.count('g')))
a.append(str(x.count('h')))
a.append(str(x.count('i')))
a.append(str(x.count('j')))
a.append(str(x.count('k')))
a.append(str(x.count('l')))
a.append(str(x.count('m')))
a.append(str(x.count('n')))
a.append(str(x.count('o')))
a.append(str(x.count('p')))
a.append(str(x.count('q')))
a.append(str(x.count('r')))
a.append(str(x.count('s')))
a.append(str(x.count('t')))
a.append(str(x.count('u')))
a.append(str(x.count('v')))
a.append(str(x.count('w')))
a.append(str(x.count('x')))
a.append(str(x.count('y')))
a.append(str(x.count('z')))

b= ' '.join(a)
print(b)